ARG ACCOUNT_ID
ARG OPENCV_VERSION=4.5.5
FROM ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/lambda-opencv:${OPENCV_VERSION}

ARG RUST_VERSION=1.61
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup install ${RUST_VERSION}
