AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String

Resources:
  OpenCVRustSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: opencv-rust-sample
      PackageType: Image
      ImageUri: ""
      MemorySize: 256
      Timeout: 600
      Environment:
        Variables:
          RUST_LOG: info
          RUST_BACKTRACE: 1
          RUST_LOG_STYLE: never
      Role:
        !Sub "arn:aws:iam::${AccountId}:role/lambda-opencv-rust-sample-role"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        ACCOUNT_ID: !Ref AccountId
